name: hype
description: "Hype a Social Media APp"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  persistent_bottom_nav_bar_v2: ^5.2.3
  badges: ^3.1.2
  overlap_stack: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  